version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./server/public:/var/www/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  app:
    build:
      context: ./server
    volumes:
      - ./server:/var/www
      - vendor:/var/www/vendor
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kaiba
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
volumes:
  vendor:
    driver: local
