version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./server/public:/var/www/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  app:
    build:
      context: ./server
    volumes:
      - ./server:/var/www
      - vendor:/var/www/vendor
volumes:
  vendor:
    driver: local
