version: '3.7'
services:
  nginx:
    ports:
      - "$APP_PORT:80"
  app:
    build:
      target: php-fpm-prod
    depends_on:
      - node
  db:
    environment:
      MYSQL_DATABASE: laravel-docker-example
  node:
    build:
      context: laravel
      dockerfile: node.Dockerfile
      target: front-prod
