version: '3.7'
services:
  nginx:
    ports:
      - "$APP_PORT:80"
    volumes:
      - ./laravel/public:/var/www/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  app:
    volumes:
      - ./laravel:/var/www
      - vendor:/var/www/vendor
  db:
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel-docker-example
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
volumes:
  vendor:
    driver: local
