version: '3.6'
services:
  nginx:
    build:
      context: nginx
    depends_on:
      - app
  app:
    build:
      context: ./laravel
    depends_on:
      - db
  db:
    build:
      context: mysql
