version: '3.7'
services:
  nginx:
    ports:
      - "$APP_PORT:80"
    volumes:
      - ./laravel/public:/var/www/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  app:
    build:
      target: php-fpm-dev
    volumes:
      - ./laravel:/var/www
      - vendor:/var/www/vendor
  db:
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel-docker-example
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    healthcheck:
      test: "CMD mysqladmin ping -u user -pppassword -h localhost || exit 1"
      timeout: 20s
      retries: 10
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql:/var/lib/mysql
  node:
    build:
      context: laravel
      dockerfile: node.Dockerfile
      target: front-dev
    command: 'tail -f /dev/null'
    volumes:
      - ./laravel:/code
      - node_modules:/code/node_modules

volumes:
  vendor:
  mysql:
  node_modules:
