version: 2.1
jobs:
  build:
    machine:
      image: circleci/classic:201808-01
    working_directory: ~/laravel-docker-example
    steps:
      - run: type docker-compose
      - run: docker -v
      - run: docker-compose -v
      - checkout
      - restore_cache:
          keys:
            - v3
          paths:
            - ~/caches/images.tar
      - run:
          command: |
            if [[ -e ~/caches/images.tar ]]; then
              docker load -i ~/caches/images.tar
            fi
          name: docker load
      - run: cp .env.local .env
      - run: docker-compose build
      - run: mkdir -p ~/caches
      - run: docker images --filter "dangling=false" --format "{{.Repository}}:{{.Tag}}"
      - run:
          command: |
            if [[ ! -e ~/caches/images.tar ]]; then
              docker save -o ~/caches/images.tar $(docker images --filter "dangling=false" --format "{{.Repository}}:{{.Tag}}")
            fi
          name: docker save
      - save_cache:
          key: v3
          paths:
            - ~/caches/images.tar

      - run: cp laravel/.env{.example,}
      - run: docker-compose up -d
      - run: docker-compose exec db mysqladmin ping -u user -ppassword -h localhost
      - run:
          command: docker-compose exec node npm test
          name: npm test
      - run: docker-compose exec app php artisan key:generate
      - run: docker-compose exec app php artisan migrate
      - run: docker-compose down
