version: 2.1
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - checkout
      - restore_cache:
          keys:
            - v1-{{ checksum "laravel/composer.lock" }}-{{ checksum "laravel/package-lock.json" }}
          paths:
            - ~/caches/images.tar
      - run:
          command: |
            if [[ -e ~/caches/images.tar ]]; then
              docker load -i ~/caches/images.tar
            fi
          name: docker load
      - run: cp .env.local .env
      - run:
          command: docker-compose run --rm node npm test
          name: npm test
      - run: docker-compose run --rm app php artisan migrate
      - run: mkdir -p ~/caches
      - run:
          command: |
            if [[ ! -e ~/caches/images.tar ]]; then
              docker save -o ~/caches/images.tar $(docker images --filter "dangling=false" --format "{{.Repository}}:{{.Tag}}")
            fi
          name: docker save
      - save_cache:
          key: v1-{{ checksum "laravel/composer.lock" }}-{{ checksum "laravel/package-lock.json" }}
          paths:
            - ~/caches/images.tar
